/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppPaymentRouteImport } from './routes/_app.payment'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppReceiptIdRouteImport } from './routes/_app.receipt.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRoute = AppPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptIdRoute = AppReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/orders': typeof AppOrdersRoute
  '/payment': typeof AppPaymentRoute
  '/payroll': typeof AppPayrollRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/receipt/$id': typeof AppReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/orders': typeof AppOrdersRoute
  '/payment': typeof AppPaymentRoute
  '/payroll': typeof AppPayrollRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/receipt/$id': typeof AppReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/payment': typeof AppPaymentRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/receipt/$id': typeof AppReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit'
    | '/employees'
    | '/inventory'
    | '/orders'
    | '/payment'
    | '/payroll'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit'
    | '/employees'
    | '/inventory'
    | '/orders'
    | '/payment'
    | '/payroll'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/employees'
    | '/_app/inventory'
    | '/_app/orders'
    | '/_app/payment'
    | '/_app/payroll'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment': {
      id: '/_app/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AppPaymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipt/$id': {
      id: '/_app/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof AppReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPaymentRoute: typeof AppPaymentRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPosRoute: typeof AppPosRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppReceiptIdRoute: typeof AppReceiptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPaymentRoute: AppPaymentRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPosRoute: AppPosRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppReceiptIdRoute: AppReceiptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
